### ISSUE TITLE
Disabling certificate validation

### ISSUE THREAD

**Issue by darleybarreto** [JuliaLang/juliaup#170]
I folks, I tried to install julia 1.6.4 on a Windows 10 machine with some security constraints and I got this error

```bash
$ juliaup add 1.6.4
Installing Julia 1.6.4+0 (x64).
Error: Failed to download from url `https://julialang-s3.julialang.org/bin/winnt/x64/1.6/julia-1.6.4-win64.tar.gz`

Caused by:
	0: https://julialang-s3.julialang.org/bin/winnt/x64/1.6/julia-1.6.4-win64.tar.gz: Connection Failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
	1: invalid peer certificate contents: invalid peer certificate: UnknownIssuer
```

Would it be possible to disable certificate validation?

**Comment by davidanthoff** [comment]
I don't think so, that is really the only defense we have against some really bad attack vectors at the moment. If we were to disable this, anyone between your machine and the server where the files are hosted could just inject whatever they wanted and send you that. I think what this error suggests is that your system doesn't rust the CA issuer that created the certificate for the domain from which we are fetching the data. Unclear to me why that would be the case, maybe @staticfloat has an idea?

**Comment by darleybarreto** [comment]
I see. I wonder what rustup do, then, because I was able to install it here without issues.

**Comment by davidanthoff** [comment]
Maybe their certificate was issued by a different authority that is actually whitelisted on your system?

Also, note to self: I should check how the Rust crate we are using is actually handling this. I'm assuming it is just looking at some system store of whitelisted certificate authorities, but we could double check.

**Comment by staticfloat** [comment]
Both of the certificates are valid; so either the root is not trusted by your system for some reason (does going there in a browser work for you?), or someone is indeed MITM'ing you.  :P

**Comment by darleybarreto** [comment]
> does going there in a browser work for you?

Yes, that works.

**Comment by StefanKarpinski** [comment]
The best option is to use a native system TLS engine which is both more secure (does certificate revocation checks on Windows and macOS) and is more likely to have MITM firewall certs added to it by the IT department. If you can point me at where the code for doing the downloads that's failing is, I might be able to save you some pain since I've already been through a lot of this for Julia itself.

**Comment by davidanthoff** [comment]
We use the `ureq` create for downloads, and it has a section that goes into quite some detail how certificates are handled: https://crates.io/crates/ureq#tls If I understand that correctly, we are currently _not_ using the OS store for certificates, but could fairly easily (hopefully) change that.

**Comment by DNF2** [comment]
Is there any update on this? Or any workaround? I am running into this when trying to update to 1.7.3/1.8.0-rc1.

**Comment by davidanthoff** [comment]
I just merged a PR so that on Windows and Mac we now use the native tls facilities of the OS.

**Comment by darleybarreto** [comment]
I can confirm this works now, thank you :)

**Comment by peteristhegreat** [comment]
This is still an issue for me.  Right now the IT dept does a MitM certificate not managed in the native OS cert chain somehow.

Most of my curl commands I have to add `-k` to get it to ignore the certificate errors.

```
$ brew install juliaup  # this works
$ julia --version
Checking for new Julia versions
Error: Failed to run `run_command_add` from the `run_command_initial_setup_from_launcher` command.

Caused by:
    0: Failed to update versions db.
    1: Failed to download current version db version.
    2: Failed to download from url `https://julialang-s3.julialang.org/juliaup/RELEASECHANNELDBVERSION`.
    3: error sending request for url (https://julialang-s3.julialang.org/juliaup/RELEASECHANNELDBVERSION)
    4: client error (Connect)
    5: The certificate was not trusted.
Error: The Julia launcher failed to figure out which juliaup channel to use.
```

Adding a cert bypass like `-k` would be really helpful.  Right now juliaup doesn't work for me on my mac.
