### ISSUE TITLE
Julia launcher can't find other versions in VS-Code

### ISSUE THREAD

**Issue by MarcMush** [JuliaLang/juliaup#179]
The "julia" launched by vscode (Julia Language Server) can't find other versions of julia. The version seems stuck in 1.6.2 for the version release and `juliaup update release` doesn't fix it. The terminal of vscode does launch the correct version:

![julia version2](https://user-images.githubusercontent.com/35898736/143877477-85565ad8-9da6-465a-8891-583c52cded26.PNG)

Also, when trying to specify a version different than the default juliaup profile, the version seems to be parsed correctly but not found:
![julia version3](https://user-images.githubusercontent.com/35898736/143877608-bf81c83f-aeca-4e28-9520-015236bebc24.PNG)

It kinda looks like I might have 2 `juliaup`s installed but I only downloaded it from the windows store so I don't think it's the case
I have only one `julia` in my `PATH`:
```
PS C:\Program Files\WindowsApps> where.exe julia
C:\Users\mittel\AppData\Local\Microsoft\WindowsApps\julia.exe
```

**Comment by MarcMush** [comment]
it *really* looks like vscode is using another julia launcher

when specifying another `default`, it's still the `release` that is launched

![julia version4](https://user-images.githubusercontent.com/35898736/143880284-5eba3ed8-4294-4d93-8b85-338646a870e3.PNG)

**Comment by MarcMush** [comment]
it became even worst with the 1.7 update, it can't launch at all

![image](https://user-images.githubusercontent.com/35898736/144592491-ff52c53b-89e8-439e-b759-5ddf7e7bc9c0.png)
`Le chemin d'accès spécifié est introuvable` means it can't find the file

**Comment by RahMac02** [comment]
Seeing the same error in Julia v1.7.0, Julia-VSCode v1.5.6.

**Comment by kaltsoplyn** [comment]
Ok, took another look at this today. There, indeed, seem to be two Julias installed, one in
`C:\Users\kaltsoplyn\AppData\Local\Microsoft\WindowsApps\julia.exe` 
and another in
`C:\Users\kaltsoplyn\.julia\juliaup\julia-1.7.0+0~x64\bin\julia.exe`
Are these the same? I don't know.
[BTW, in my PATH there's no Julia entry. I thought `juliaup` handles that part, so I touched nothing, and it worked - until recently.]

In any case, for the time being, my sub-optimal workaround to get the Julia LS to start is to set the Julia executable path in the extension settings to the latter binary, `C:\Users\kaltsoplyn\.julia\juliaup\julia-1.7.0+0~x64\bin\julia.exe`. Leaving the field empty results to the LS crashing, with this error message: 
![image](https://user-images.githubusercontent.com/47606476/146350536-0e85689a-38a7-4456-949d-916624c024fa.png)
presumably because it calls the WindowsApps `julia.exe`?
(although when I start a Julia REPL from VSCode commands, it fires up the `.julia/juliaup` version, which is the executable that works when I use it in the settings)

**Comment by MarcMush** [comment]
I believe the `julia` in `WindowsApps` is the julia launcher, which takes the `+version` argument to chose which version of julia to launch, the other one is the 1.7.0 version of julia, so when you specify this binary to vs code, it launches directly julia without juliaup (that's my way of fixing it too)

**Comment by kaltsoplyn** [comment]
@MarcMush yeap, figured it'd be something like that. Question is what's changed? it used to work without specifying a hard path in the settings, and it was certainly better that way.

**Comment by davidanthoff** [comment]
I'm pretty positive that https://github.com/julia-vscode/julia-vscode/pull/2374 will fix this. I'll try to merge that today and then we just need to get a new extension version out.

The background story here is that we start the language server with a modified `JULIA_DEPOT` argument, and `juliaup` picks that up. So the Julia instance that we start for the language server then doesn't have access to your default `juliaup` configuration which is in `.julia/juliaup` because it starts to read its configuration from the folder that `JULIA_DEPOT` points to. We do all of the `JULIA_DEPOT` to isolate the language server from any configuration users might have around Julia packages etc, but in this case the isolation is going a bit too far.

And @MarcMush's explanation is correct: the `julia.exe`  in `Appdata\Local|\Microsoft\WindowsApps` is the one that starts the julia launcher that ships with `juliaup`, and that folder is also on the `PATH`. I think the `julia.exe` there is actually a symbolic link to the "real" `julialauncher.exe` which is installed in yet another location. All those parts are handled by the MSIX installer on Windows for us :)

**Comment by kaltsoplyn** [comment]
@davidanthoff thanks for the update, and, since I'm at it, thank you (and all other contributors, of course) for all the great work you've done and keep doing, and all the time and effort you've put into juliaup and the VSCode extension and everything.

**Comment by davidanthoff** [comment]
I think this should now be fixed with the latest VS Code extension release, can we close this issue? Would be great if someone who had this problem could confirm that things are OK now.

**Comment by kaltsoplyn** [comment]
Confirmed from my side:
VSCode v.1.63.2 (Windows_NT x64 10.0.19044) & Julia extension 1.5.8 --> everything ok.
Hopefully it's ok for the OP, too. @MarcMush?

**Comment by MarcMush** [comment]
I'll test it when I get back on my work PC in january

**Comment by MarcMush** [comment]
are versions completely ignored now ? is it intended ?
![image](https://user-images.githubusercontent.com/35898736/148047680-769add8e-2e80-4ded-93d9-358b99ef31a2.png)

**Comment by davidanthoff** [comment]
Yes, a bug in the extension. It is fixed on `Master` and will hopefully ship soon.

**Comment by MarcMush** [comment]
the initial issue is still here for me

![image](https://user-images.githubusercontent.com/35898736/149122881-714d5fd0-6352-4c36-99ff-aa9bf25bd21d.png)

![image](https://user-images.githubusercontent.com/35898736/149122941-d3b1f1c1-fc62-452e-85cd-de82e7db9aa9.png)

**Comment by MarcMush** [comment]
Can this issue be re-opened?

**Comment by davidanthoff** [comment]
What version of the Julia extension for VS Code are you using?

**Comment by MarcMush** [comment]
1.5.9, it says I'm up to date
1.5.2 for the julia launcher (with windows store)

and also, giving the complete path doesn't help:
![image](https://user-images.githubusercontent.com/35898736/149635066-0a88936b-7386-4755-a534-7633f7b50af2.png)

**Comment by davidanthoff** [comment]
Does it work if you just leave `julia.executablePath` empty entirely? I think I actually understand why it doesn't work if you have some value in that field, but I think the version that ships right now should work if you just leave that configuration setting empty.

I think what I'll have to do is actually add another configuration setting to the extension called `julia.channel` that allows one to specify a channel to be used for the Juliaup scenario...

**Comment by MarcMush** [comment]
yes, it works if it's empty
a `julia.channel` setting would work for me
btw I don't really care about the version of the julia language server, but it's the same setting for it and the terminal

**Comment by davidanthoff** [comment]
I think what should work at the moment is that you leave the setting empty, and then change the default channel with juliaup. That still only gives you one global choice, though...

**Comment by MarcMush** [comment]
what I do for now is put the complete path of the julia version I want:
```json
{
    "julia.executablePath": "C:\\Users\\mittel\\.julia\\juliaup\\julia-1.6.5+0~x64\\bin\\julia.exe"
}
```

**Comment by davidanthoff** [comment]
I've thought a bit more about this, and I think the solution to this is probably to leave everything as is :)

So that would mean:
- if `julia.executablePath` is empty, the extension will use the `juliaup default` channel. If one wants to configure a different machine wide default version, one does _not_ have an option in the extension, instead one has to do that by changing the system default version via `juliaup default`. 
- For a workspace specific override we should just come up with a generic `juliaup` solution for that, and then the VS Code extension should pick that up, instead of having a VS Code extension specific solution for that.

So I think I'm going to close this issue for now.
